import React, { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertTriangle, Archive, Bell, Building2, CalendarDays, Check, ChevronRight,
  ClipboardCheck, Command, FileCheck2, FileText, Gauge, Grid2X2, HardHat, Home,
  Layers3, Loader2, LockKeyhole, LogOut, Menu, Moon, PackageCheck, Plus, Search,
  Settings, ShieldCheck, ShoppingCart, Sparkles, Sun, Truck, Users, Warehouse, Workflow, X
} from 'lucide-react';
import { supabase, isSupabaseConfigured } from './lib/supabase';

const AREAS = [
  ['my-work','My Work',Home],['customers','Customers',Building2],['sales','Sales',ShoppingCart],
  ['projects','Projects',Layers3],['fulfillment','Fulfillment',PackageCheck],['field','Field',HardHat],
  ['contracts','Contracts',FileCheck2],['reports','Reports',Gauge],['administration','Administration',Settings]
];
const CONTEXT = {
  'my-work':['Command Center','My Queue','Approvals','Exceptions','Schedule','Activity'],
  customers:['Customer Directory','Facility Directory','Contacts','Needs Review','Merge Center'],
  sales:['Sales Requests','Estimating Queue','Quote Playbook','Proposal Review','MatBuilder Pro','FCC Connect'],
  projects:['Project Portfolio','Design & Approval','Schedule','Crew Requirements','Closeout'],
  fulfillment:['OrderDNA','Purchasing','Receiving','Warehouse','Staging & Loading','FinishLine Delivery'],
  field:['Today','CrewFlow Planner','Availability','Time Off','Installation Proof','Safety & Incidents'],
  contracts:['Contract Portfolio','SOV & Pay Apps','Compliance','Waivers','Payments','Contract Reports'],
  reports:['ScoreCenter','Pipeline','Operational Health','Contract Health','Exceptions'],
  administration:['Price Book','Vendors','Users & Roles','Workflow Builder','Templates','Documents','Integrations','Audit']
};
const FLOW = ['Request received','Scope development','Pricing','Internal review','Sales review','Sent to customer','Approved','Project / Order','Purchasing','Receiving','Staging','Delivery / Install','Accounting ready'];
const DEMO = {
  customers:[
    {id:'demo-c1',customer_number:'CUS-1048',name:'Saranac Community Schools',tier:'Championship Partner',status:'active',health:'active',address_line1:'225 Pleasant St',city:'Saranac',state:'MI'},
    {id:'demo-c2',customer_number:'CUS-1032',name:'Morrice Area Schools',tier:'Preferred',status:'active',health:'active',address_line1:'111 E Mason St',city:'Morrice',state:'MI'},
    {id:'demo-c3',customer_number:'CUS-1019',name:'Mt. Morris Consolidated Schools',tier:'Championship Partner',status:'active',health:'at_risk',address_line1:'12356 Walter St',city:'Mt Morris',state:'MI'}
  ],
  facilities:[
    {id:'demo-f1',customer_id:'demo-c1',name:'Saranac Jr/Sr High School',facility_type:'High School',status:'active'},
    {id:'demo-f2',customer_id:'demo-c1',name:'Saranac Elementary',facility_type:'Elementary School',status:'active'},
    {id:'demo-f3',customer_id:'demo-c2',name:'Morrice High School',facility_type:'High School',status:'active'}
  ],
  spaces:[
    {id:'demo-s1',facility_id:'demo-f1',name:'Main Gym',space_type:'Gymnasium',floor_system:'Maple sports floor',condition:'Good'},
    {id:'demo-s2',facility_id:'demo-f1',name:'Auxiliary Gym',space_type:'Gymnasium',floor_system:'Maple sports floor',condition:'Watch'},
    {id:'demo-s3',facility_id:'demo-f2',name:'Gymnasium',space_type:'Gymnasium',floor_system:'Synthetic',condition:'Good'}
  ],
  tasks:[
    {id:'demo-t1',title:'Review Saranac pay application',status:'in_progress',priority:'high',due_at:new Date().toISOString(),related_type:'contract'},
    {id:'demo-t2',title:'Schedule Morrice delivery',status:'ready',priority:'high',due_at:new Date().toISOString(),related_type:'delivery'},
    {id:'demo-t3',title:'Approve logo mat proof',status:'waiting',priority:'normal',due_at:null,related_type:'mat_proof'}
  ],
  sales_requests:[
    {id:'demo-r1',request_number:'REQ-26084',customer_id:'demo-c1',facility_id:'demo-f1',space_id:'demo-s1',request_type:'service',title:'Summer gym refinish',need_summary:'Sand, repaint game lines and refinish main gym.',status:'internal_review',priority:'high'},
    {id:'demo-r2',request_number:'REQ-26085',customer_id:'demo-c2',facility_id:'demo-f3',request_type:'resale',title:'Custodial supply replenishment',need_summary:'Chemicals, frames, handles and mop heads.',status:'pricing',priority:'normal'}
  ],
  quotes:[{id:'demo-q1',quote_number:'Q-26194',sales_request_id:'demo-r1',customer_id:'demo-c1',facility_id:'demo-f1',status:'sales_review',total:184250,current_version:3}],
  projects:[{id:'demo-p1',project_number:'PRJ-26041',customer_id:'demo-c1',facility_id:'demo-f1',name:'Saranac Main Gym Refinish',project_type:'Sand & Refinish',status:'planning',planned_start:'2026-08-10',planned_finish:'2026-08-21',accounting_ready:false}],
  orders:[{id:'demo-o1',order_number:'ORD-26101',customer_id:'demo-c2',facility_id:'demo-f3',order_type:'resale',status:'approved',fulfillment_status:'purchasing',total:12870,accounting_ready:false}],
  purchase_orders:[{id:'demo-po1',po_number:'PO-26088',order_id:'demo-o1',status:'confirmed',promised_on:'2026-08-08',total:6400,exception_status:null}],
  delivery_tickets:[{id:'demo-d1',ticket_number:'DEL-26072',order_id:'demo-o1',customer_id:'demo-c2',facility_id:'demo-f3',status:'ready_to_schedule',proof_complete:false}],
  contracts:[{id:'demo-ct1',contract_number:'CT-26012',project_id:'demo-p1',customer_id:'demo-c1',general_contractor:'Saranac Community Schools',contract_value:184250,billed_to_date:92125,paid_to_date:46062,status:'active'}]
};

const fmtMoney = v => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v||0));
const pretty = v => String(v||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const cx = (...x)=>x.filter(Boolean).join(' ');

export default function App(){
  const [session,setSession]=useState(null);
  const [booting,setBooting]=useState(isSupabaseConfigured);
  const [theme,setTheme]=useState(localStorage.getItem('fcc-theme')||'light');
  const [area,setArea]=useState('my-work');
  const [context,setContext]=useState('Command Center');
  const [rail,setRail]=useState(true);
  const [searchOpen,setSearchOpen]=useState(false);
  const [noticeOpen,setNoticeOpen]=useState(false);
  const [createOpen,setCreateOpen]=useState(false);
  const [data,setData]=useState(DEMO);
  const [loading,setLoading]=useState(false);
  const [selectedCustomer,setSelectedCustomer]=useState('demo-c1');
  const [selectedRequest,setSelectedRequest]=useState('demo-r1');
  const [selectedQuote,setSelectedQuote]=useState('demo-q1');
  const [toast,setToast]=useState('');

  useEffect(()=>{
    if(!supabase){setBooting(false);return;}
    supabase.auth.getSession().then(({data:{session}})=>{setSession(session);setBooting(false);});
    const {data:listener}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);});
    return ()=>listener.subscription.unsubscribe();
  },[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('fcc-theme',theme)},[theme]);
  useEffect(()=>{setContext(CONTEXT[area][0])},[area]);
  useEffect(()=>{if(session) loadWorkspace();},[session]);
  useEffect(()=>{
    const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}if(e.key==='Escape'){setSearchOpen(false);setNoticeOpen(false);setCreateOpen(false)}};
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  },[]);

  async function loadWorkspace(){
    setLoading(true);
    const tables=['customers','facilities','spaces','tasks','sales_requests','quotes','projects','orders','purchase_orders','delivery_tickets','contracts'];
    const results=await Promise.all(tables.map(t=>supabase.from(t).select('*').order('created_at',{ascending:false}).limit(100)));
    const next={...DEMO};
    results.forEach((r,i)=>{if(!r.error&&r.data?.length)next[tables[i]]=r.data});
    setData(next);setLoading(false);
    if(next.customers[0])setSelectedCustomer(next.customers[0].id);
    if(next.sales_requests[0])setSelectedRequest(next.sales_requests[0].id);
    if(next.quotes[0])setSelectedQuote(next.quotes[0].id);
  }
  function flash(message){setToast(message);setTimeout(()=>setToast(''),2600)}
  async function createTask(payload){
    if(session&&supabase){const {error}=await supabase.from('tasks').insert({title:payload.title,description:payload.description,status:'ready',priority:payload.priority,due_at:payload.due_at||null,created_by:session.user.id});if(error)throw error;await loadWorkspace();}
    else setData(d=>({...d,tasks:[{id:crypto.randomUUID(),status:'ready',...payload},...d.tasks]}));
    flash('Task created in the shared queue');
  }
  async function completeTask(id){
    if(session&&supabase){await supabase.from('tasks').update({status:'complete',completed_at:new Date().toISOString()}).eq('id',id);await loadWorkspace();}
    else setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,status:'complete'}:t)}));
    flash('Task completed');
  }
  async function createRequest(payload){
    const record={...payload,status:'request_received',qualification_status:'needs_review',priority:payload.priority||'normal'};
    if(session&&supabase){record.requested_by=session.user.id;const {error}=await supabase.from('sales_requests').insert(record);if(error)throw error;await loadWorkspace();}
    else setData(d=>({...d,sales_requests:[{id:crypto.randomUUID(),request_number:`REQ-${Date.now().toString().slice(-5)}`,...record},...d.sales_requests]}));
    setArea('sales');setContext('Sales Requests');flash('Sales request created from FacilityDNA context');
  }
  async function advanceRecord(table,id,status){
    if(session&&supabase){await supabase.from(table).update({status}).eq('id',id);await loadWorkspace();}
    else setData(d=>({...d,[table]:d[table].map(x=>x.id===id?{...x,status}:x)}));
    flash(`Advanced to ${pretty(status)}`);
  }

  if(booting)return <div className="auth-screen"><Loader2 className="spin"/><h2>Loading FCC Ops</h2></div>;
  if(isSupabaseConfigured&&!session)return <AuthScreen/>;

  const body = renderWorkspace({area,context,data,setData,selectedCustomer,setSelectedCustomer,selectedRequest,setSelectedRequest,selectedQuote,setSelectedQuote,completeTask,advanceRecord,setCreateOpen,flash});
  return <div className={cx('fcc-app',theme==='dark'&&'dark')}>
    <header className="platform-header">
      <div className="brand-zone"><button className="icon-button" aria-label="Toggle contextual navigation" onClick={()=>setRail(!rail)}><Menu/></button><div className="fcc-badge">FCC</div><div><strong>FCC Ops</strong><small>The Sports Floor Pros</small></div></div>
      <nav className="global-nav" aria-label="Major platform areas">{AREAS.map(([id,label,Icon])=><button key={id} className={area===id?'active':''} onClick={()=>setArea(id)}><Icon/><span>{label}</span></button>)}</nav>
      <div className="header-tools"><button className="command-button" onClick={()=>setSearchOpen(true)}><Search/><span>Search FCC Ops</span><kbd>Ctrl K</kbd></button><button className="icon-button" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</button><button className="icon-button notice-button" onClick={()=>setNoticeOpen(!noticeOpen)}><Bell/><i>{data.tasks.filter(t=>t.status!=='complete').length}</i></button><button className="primary small" onClick={()=>setCreateOpen(true)}><Plus/>Create</button><div className="user-chip"><ShieldCheck/><span>{session?.user?.email||'Development workspace'}</span>{session&&<button aria-label="Sign out" onClick={()=>supabase.auth.signOut()}><LogOut/></button>}</div></div>
    </header>
    <aside className={cx('context-rail',!rail&&'collapsed')}><div className="rail-heading"><small>{AREAS.find(x=>x[0]===area)?.[1]}</small><strong>{context}</strong></div><nav>{CONTEXT[area].map(item=><button key={item} className={context===item?'active':''} onClick={()=>setContext(item)}><span>{item}</span><ChevronRight/></button>)}</nav><div className="rail-footer"><Activity/><div><small>Platform status</small><strong>{loading?'Synchronizing':'All systems ready'}</strong></div></div></aside>
    <main className={cx('work-surface',!rail&&'wide')}>{loading&&<div className="sync-line"><Loader2 className="spin"/> Syncing production records</div>}{body}</main>
    {noticeOpen&&<NotificationCenter tasks={data.tasks} close={()=>setNoticeOpen(false)} goTask={()=>{setArea('my-work');setContext('My Queue');setNoticeOpen(false)}}/>}
    {searchOpen&&<GlobalSearch data={data} close={()=>setSearchOpen(false)} navigate={(type,id)=>{if(type==='customer'){setSelectedCustomer(id);setArea('customers');setContext('Customer Directory')}if(type==='request'){setSelectedRequest(id);setArea('sales');setContext('Sales Requests')}setSearchOpen(false)}}/>}
    {createOpen&&<CreateCenter data={data} close={()=>setCreateOpen(false)} createTask={createTask} createRequest={createRequest}/>} 
    {toast&&<div className="toast"><Check/>{toast}</div>}
  </div>;
}

function AuthScreen(){
  const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin,data:{full_name:email.split('@')[0]}}});setBusy(false);if(error)setError(error.message);else setSent(true)}
  return <div className="auth-screen"><div className="auth-card"><div className="auth-brand"><span>FCC</span><div><strong>FCC Ops</strong><small>One operating system. One source of truth.</small></div></div>{sent?<div className="auth-message"><Sparkles/><h2>Check your email</h2><p>A secure sign-in link was sent to <b>{email}</b>.</p></div>:<form onSubmit={submit}><span>AUTHORIZED TEAM ACCESS</span><h1>Enter the championship workspace.</h1><p>Use your Floor Care Concepts email address. FCC Ops will securely sign you in without a separate password.</p><label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@floorcareconcepts.net"/></label>{error&&<div className="error-box">{error}</div>}<button className="primary" disabled={busy}>{busy?<Loader2 className="spin"/>:<LockKeyhole/>} Send secure sign-in link</button></form>}</div></div>
}

function renderWorkspace(p){
  const map={
    'my-work':<CommandCenter {...p}/>,'customers':<CustomerIntelligence {...p}/>,'sales':<SalesWorkspace {...p}/>,
    'projects':<ProjectsWorkspace {...p}/>,'fulfillment':<FulfillmentWorkspace {...p}/>,'field':<FieldWorkspace {...p}/>,
    'contracts':<ContractsWorkspace {...p}/>,'reports':<ReportsWorkspace {...p}/>,'administration':<AdministrationWorkspace {...p}/>
  };return map[p.area];
}
function PageIntro({eyebrow,title,copy,actions}){return <div className="page-intro"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div><div className="page-actions">{actions}</div></div>}
function Status({value}){return <span className={cx('status-pill',String(value).replaceAll('_','-'))}>{pretty(value)}</span>}
function Empty({title,copy}){return <div className="empty"><Archive/><h3>{title}</h3><p>{copy}</p></div>}

function CommandCenter({data,completeTask,setCreateOpen}){
  const open=data.tasks.filter(t=>t.status!=='complete');
  return <><PageIntro eyebrow="COMMAND CENTER · MY WORK" title="Run today from one trusted queue." copy="Assignments, approvals, exceptions and next actions from every FCC Ops workflow." actions={<button className="primary" onClick={()=>setCreateOpen(true)}><Plus/>Create work</button>}/><section className="command-hero"><div><small>TODAY'S OPERATING PICTURE</small><h2>{open.length} actions require attention.</h2><p>Prioritized by urgency, blockage, customer impact and workflow stage.</p></div><div className="readiness"><small>OPERATIONS PULSE</small><strong>92</strong><span>Game ready</span></div></section><div className="metric-strip">{[['Due today',open.filter(t=>t.due_at).length,'Work requiring action'],['Approvals',3,'Commercial and proof reviews'],['Exceptions',2,'Vendor and schedule blockers'],['Active lifecycle records',data.sales_requests.length+data.projects.length+data.orders.length,'Across sales through accounting']].map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div><div className="work-grid"><section className="panel queue-panel"><header><div><span>PRIMARY QUEUE</span><h3>What needs to move now</h3></div></header>{open.length?open.map(t=><div className="queue-row" key={t.id}><button className="complete-control" onClick={()=>completeTask(t.id)} aria-label={`Complete ${t.title}`}><Check/></button><div><strong>{t.title}</strong><small>{pretty(t.related_type||'FCC Ops')} · {t.due_at?'Due now':'No due date'}</small></div><Status value={t.status}/><span className={cx('priority',t.priority)}>{pretty(t.priority)}</span></div>):<Empty title="Queue clear" copy="There is no open work assigned to this view."/>}</section><section className="panel"><header><div><span>WORKFLOW RAIL</span><h3>Lifecycle pressure</h3></div></header>{FLOW.slice(0,7).map((s,i)=><div className="flow-row" key={s}><span>{i+1}</span><div><strong>{s}</strong><small>{[2,4,3,2,1,5,2][i]} active records</small></div><div className="flow-bar"><i style={{width:`${[36,64,48,32,18,78,28][i]}%`}}/></div></div>)}</section></div><section className="panel activity-panel"><header><div><span>COMPANY ACTIVITY</span><h3>Recent operational changes</h3></div></header><div className="activity-grid">{[['Quote moved to Sales Review','Saranac Main Gym · Version 3'],['Order released to purchasing','Morrice custodial supplies'],['Delivery proof completed','Morrice Elementary · Signed by K. Riley'],['Pay application advanced','Saranac · Controller review complete']].map((x,i)=><article key={x[0]}><span><Activity/></span><div><strong>{x[0]}</strong><p>{x[1]}</p><small>{i*23+12} minutes ago</small></div></article>)}</div></section></>;
}

function CustomerIntelligence({context,data,selectedCustomer,setSelectedCustomer,setCreateOpen}){
  const c=data.customers.find(x=>x.id===selectedCustomer)||data.customers[0];const facilities=data.facilities.filter(f=>f.customer_id===c?.id);
  if(context==='Facility Directory')return <><PageIntro eyebrow="FACILITYDNA" title="The physical operating record." copy="Buildings, entrances, spaces, assets, instructions and service history connected to one customer."/><section className="facility-directory">{data.facilities.map(f=><article className="facility-tile" key={f.id}><span><Building2/></span><div><small>{pretty(f.facility_type)}</small><h3>{f.name}</h3><p>{data.customers.find(c=>c.id===f.customer_id)?.name}</p></div><strong>{data.spaces.filter(s=>s.facility_id===f.id).length} spaces</strong></article>)}</section></>;
  return <><PageIntro eyebrow="CUSTOMER INTELLIGENCE" title="One relationship record beneath every workflow." copy="Customer, contact, facility and operational history without duplicate lists or re-entry." actions={<button className="primary" onClick={()=>setCreateOpen(true)}><Plus/>Start request</button>}/><div className="record-layout"><section className="record-list panel"><div className="list-filter"><Search/><input placeholder="Search customers"/></div>{data.customers.map(x=><button className={x.id===c?.id?'selected':''} key={x.id} onClick={()=>setSelectedCustomer(x.id)}><span className="record-monogram">{x.name.split(' ').slice(0,2).map(w=>w[0]).join('')}</span><div><strong>{x.name}</strong><small>{x.customer_number||'Unnumbered'} · {x.tier}</small></div><Status value={x.health}/></button>)}</section>{c?<section className="record-workspace"><header className="record-header"><div className="identity-icon"><Building2/></div><div><small>{c.customer_number} · {c.tier}</small><h2>{c.name}</h2><p>{[c.address_line1,c.city,c.state].filter(Boolean).join(', ')}</p></div><div className="record-header-actions"><Status value={c.status}/><button className="secondary">Edit record</button></div></header><nav className="record-tabs"><button className="active">Overview</button><button>Contacts</button><button>Facilities</button><button>Sales</button><button>Projects</button><button>Orders</button><button>Files</button><button>Activity</button></nav><div className="record-summary"><div><small>Facilities</small><strong>{facilities.length}</strong></div><div><small>Spaces</small><strong>{facilities.reduce((n,f)=>n+data.spaces.filter(s=>s.facility_id===f.id).length,0)}</strong></div><div><small>Open requests</small><strong>{data.sales_requests.filter(r=>r.customer_id===c.id).length}</strong></div><div><small>Active work</small><strong>{data.projects.filter(r=>r.customer_id===c.id).length+data.orders.filter(r=>r.customer_id===c.id).length}</strong></div></div><div className="facility-workspace"><header><div><span>CONNECTED FACILITIES</span><h3>FacilityDNA hierarchy</h3></div><button className="secondary">Add facility</button></header>{facilities.map(f=><article className="facility-record" key={f.id}><div className="facility-identity"><span><Building2/></span><div><small>{pretty(f.facility_type)}</small><h3>{f.name}</h3></div></div><div className="space-chips">{data.spaces.filter(s=>s.facility_id===f.id).map(s=><button key={s.id}>{s.name}<small>{s.floor_system||s.space_type}</small></button>)}</div><button className="text-action">Open FacilityDNA <ChevronRight/></button></article>)}</div></section>:<Empty title="No customers" copy="Create the first customer record."/>}</div></>;
}

function SalesWorkspace({context,data,selectedRequest,setSelectedRequest,selectedQuote,setSelectedQuote,advanceRecord,setCreateOpen}){
  if(context==='Quote Playbook')return <QuotePlaybook data={data} selectedQuote={selectedQuote} setSelectedQuote={setSelectedQuote} advanceRecord={advanceRecord}/>;
  if(context==='Proposal Review')return <ProposalReview data={data} selectedQuote={selectedQuote} advanceRecord={advanceRecord}/>;
  if(context==='MatBuilder Pro')return <MatBuilder/>;
  const r=data.sales_requests.find(x=>x.id===selectedRequest)||data.sales_requests[0];
  return <><PageIntro eyebrow="SALES REQUESTS" title="Start with the customer need—not a quote form." copy="Field intake, qualification, estimating ownership and blockers remain tied to FacilityDNA." actions={<button className="primary" onClick={()=>setCreateOpen(true)}><Plus/>New request</button>}/><div className="sales-layout"><section className="request-queue panel"><header><span>ESTIMATING QUEUE</span><h3>Requests requiring action</h3></header>{data.sales_requests.map(x=><button key={x.id} className={x.id===r?.id?'selected':''} onClick={()=>setSelectedRequest(x.id)}><div><small>{x.request_number} · {pretty(x.request_type)}</small><strong>{x.title}</strong><span>{data.customers.find(c=>c.id===x.customer_id)?.name}</span></div><Status value={x.status}/></button>)}</section>{r&&<section className="request-detail"><header className="record-header"><div className="identity-icon"><ClipboardCheck/></div><div><small>{r.request_number} · {pretty(r.request_type)}</small><h2>{r.title}</h2><p>{data.customers.find(c=>c.id===r.customer_id)?.name} · {data.facilities.find(f=>f.id===r.facility_id)?.name}</p></div><Status value={r.status}/></header><div className="progress-band">{FLOW.slice(0,7).map((s,i)=><div className={i<=Math.max(0,['request_received','scope_development','pricing','internal_review','sales_review','sent_to_customer','approved'].indexOf(r.status))?'done':''} key={s}><i>{i<6?<Check/>:7}</i><span>{s}</span></div>)}</div><div className="request-canvas"><section><span>NEED & QUALIFICATION</span><h3>{r.need_summary}</h3><dl><div><dt>Facility</dt><dd>{data.facilities.find(f=>f.id===r.facility_id)?.name}</dd></div><div><dt>Space</dt><dd>{data.spaces.find(s=>s.id===r.space_id)?.name||'Multiple / not selected'}</dd></div><div><dt>Priority</dt><dd>{pretty(r.priority)}</dd></div><div><dt>Qualification</dt><dd>{pretty(r.qualification_status)}</dd></div></dl></section><aside><span>NEXT ACTION</span><h3>{r.status==='request_received'?'Qualify and assign estimator':'Continue commercial workflow'}</h3><p>Known customer and facility data will automatically flow into the quote and downstream records.</p><button className="primary" onClick={()=>advanceRecord('sales_requests',r.id,r.status==='request_received'?'scope_development':'pricing')}>Advance request <ChevronRight/></button></aside></div></section>}</div></>;
}

function QuotePlaybook({data,selectedQuote,setSelectedQuote,advanceRecord}){
  const q=data.quotes.find(x=>x.id===selectedQuote)||data.quotes[0];
  return <><PageIntro eyebrow="QUOTE PLAYBOOK" title="Build the commercial scope with operational intelligence." copy="Three-pane configuration preserves internal detail while controlling the customer-facing release."/><div className="quote-shell"><aside className="scope-nav"><header><small>QUOTE</small><strong>{q?.quote_number||'No quote selected'}</strong></header>{['Project setup','Scope & products','Labor & schedule','Freight & tax','Alternates','Clarifications','Terms'].map((x,i)=><button className={i===1?'active':''} key={x}><span>{i+1}</span>{x}<ChevronRight/></button>)}</aside><section className="quote-canvas"><header><div><span>SCOPE & PRODUCTS</span><h2>{data.sales_requests.find(r=>r.id===q?.sales_request_id)?.title||'Select a quote'}</h2></div><Status value={q?.status||'draft'}/></header><div className="configuration-table"><div className="configuration-head"><span>Description</span><span>Quantity</span><span>Unit</span><span>Price</span><span>Total</span></div>{[['Sand and refinish maple floor','9,800','SF','$8.75','$85,750'],['Game line repainting','1','LS','$18,500','$18,500'],['Logo and center court graphics','1','LS','$27,000','$27,000'],['Mobilization and protection','1','LS','$8,500','$8,500']].map(x=><div className="configuration-row" key={x[0]}>{x.map(v=><span key={v}>{v}</span>)}</div>)}</div><button className="add-line"><Plus/>Add scope item from Price Book</button></section><aside className="price-intelligence"><span>PRICE INTELLIGENCE</span><h3>Selected quote</h3><dl><div><dt>Version</dt><dd>{q?.current_version||1}</dd></div><div><dt>Subtotal</dt><dd>{fmtMoney((q?.total||184250)*.94)}</dd></div><div><dt>Freight & tax</dt><dd>{fmtMoney((q?.total||184250)*.06)}</dd></div><div className="total"><dt>Total</dt><dd>{fmtMoney(q?.total||184250)}</dd></div></dl><div className="readiness-box"><Check/><div><strong>Commercial readiness</strong><span>No unresolved pricing blockers.</span></div></div><button className="primary" onClick={()=>q&&advanceRecord('quotes',q.id,'internal_review')}>Send to internal review</button></aside></div></>;
}
function ProposalReview({data,selectedQuote,advanceRecord}){const q=data.quotes.find(x=>x.id===selectedQuote)||data.quotes[0];return <><PageIntro eyebrow="PROPOSAL REVIEW STUDIO" title="Review exactly what the customer will receive." copy="Document preview, recipient controls, version history and approval readiness remain side by side."/><div className="proposal-studio"><section className="proposal-preview"><div className="proposal-paper"><header><div className="fcc-doc-mark">FCC</div><div><strong>Floor Care Concepts</strong><small>The Sports Floor Pros</small></div><span>{q?.quote_number}</span></header><h1>Championship Floor Proposal</h1><p className="customer-line">Prepared for {data.customers.find(c=>c.id===q?.customer_id)?.name}</p><div className="proposal-section"><h3>Project Scope</h3><p>Complete surface preparation, sanding, athletic game-line refinishing and professional finish system application for the selected FacilityDNA space.</p></div><div className="proposal-price"><span>Proposal Total</span><strong>{fmtMoney(q?.total||184250)}</strong></div><div className="signature-line">Customer acceptance and electronic signature</div></div></section><aside className="review-controls"><span>RELEASE CONTROL</span><h2>Version {q?.current_version||1}</h2><Status value={q?.status}/><div className="control-group"><small>Recipients</small><div className="recipient">Athletic Director <span>Primary approver</span></div><div className="recipient">Business Office <span>Copy</span></div></div><div className="control-group"><small>Readiness</small>{['Scope complete','Pricing approved','Terms attached','Facility requirements resolved'].map(x=><div className="check-line" key={x}><Check/>{x}</div>)}</div><button className="primary" onClick={()=>q&&advanceRecord('quotes',q.id,'sent_to_customer')}>Release to customer</button><button className="secondary">Request revision</button></aside></div></>}
function MatBuilder(){return <><PageIntro eyebrow="MATBUILDER PRO" title="Purpose-built mat design and production control." copy="Field measurements become optimized roll layouts, customer proofs and permanent reorder records."/><div className="matbuilder"><aside><span>MAT PROJECT</span><h2>Main Entrance System</h2>{['Field intake','Geometry','Roll layout','Pricing','Vendor proof','Customer approval','Production'].map((x,i)=><button className={i===2?'active':''} key={x}><span>{i+1}</span>{x}</button>)}</aside><section className="mat-canvas"><div className="roll"><small>13′ 2″ ROLL</small><div className="mat-shape wide">Mat A · 6′ × 10′</div><div className="mat-shape">Mat B · 4′ × 8′</div><div className="scrap">Sellable scrap</div></div><footer><span>Material utilization</span><strong>91.4%</strong><span>Waste</span><strong>8.6%</strong></footer></section><aside className="mat-price"><span>PRODUCTION INTELLIGENCE</span><h3>Optimized plan</h3><dl><div><dt>Roll width</dt><dd>13′ 2″</dd></div><div><dt>Billable material</dt><dd>128 SF</dd></div><div><dt>Sellable scrap</dt><dd>12 SF</dd></div><div><dt>Edging</dt><dd>Black · 4 sides</dd></div></dl><button className="primary">Create vendor work order</button></aside></div></>}

function ProjectsWorkspace({data}){return <><PageIntro eyebrow="PROJECTS" title="Approved work becomes an executable plan." copy="Design dependencies, schedule, crew requirements, milestones and closeout remain connected to the accepted scope."/><section className="portfolio">{data.projects.length?data.projects.map(p=><article key={p.id}><header><div><small>{p.project_number} · {pretty(p.project_type)}</small><h2>{p.name}</h2><p>{data.customers.find(c=>c.id===p.customer_id)?.name}</p></div><Status value={p.status}/></header><div className="project-stage"><div className="done">Approved scope</div><div className="active">Planning</div><div>Material ready</div><div>Scheduled</div><div>Field work</div><div>Closeout</div></div><div className="project-details"><span><CalendarDays/> {p.planned_start||'Not scheduled'} → {p.planned_finish||'Open'}</span><span><Users/> Crew requirements pending</span><span><FileText/> 8 connected documents</span></div><footer><button className="secondary">Open project</button><button className="primary">Resolve next blocker</button></footer></article>):<Empty title="No projects" copy="Approved proposals will create projects here."/>}</section></>}
function FulfillmentWorkspace({context,data,advanceRecord}){
 if(context==='Purchasing')return <><PageIntro eyebrow="PURCHASING" title="Vendor commitments with visible exceptions." copy="PO stage, vendor dates, documents and affected order context remain together."/><section className="po-list">{data.purchase_orders.map(po=><article key={po.id}><header><div><small>{po.po_number}</small><h3>{pretty(po.status)}</h3></div><Status value={po.exception_status||'on_track'}/></header><dl><div><dt>Vendor</dt><dd>Matter Surfaces</dd></div><div><dt>Promised</dt><dd>{po.promised_on||'Pending'}</dd></div><div><dt>Total</dt><dd>{fmtMoney(po.total)}</dd></div></dl><button className="primary" onClick={()=>advanceRecord('purchase_orders',po.id,'received')}>Open receiving</button></article>)}</section></>;
 if(context==='Receiving')return <Receiving data={data}/>;
 if(context==='Warehouse'||context==='Staging & Loading')return <WarehouseWorkspace data={data}/>;
 if(context==='FinishLine Delivery')return <DeliveryWorkspace data={data} advanceRecord={advanceRecord}/>;
 return <><PageIntro eyebrow="ORDERDNA" title="The accepted commercial record becomes the execution record." copy="Requirements split into purchasing, warehouse, delivery, installation and accounting actions without duplicate entry."/><section className="order-list">{data.orders.map(o=><article key={o.id}><header><div><small>{o.order_number} · {pretty(o.order_type)}</small><h2>{data.customers.find(c=>c.id===o.customer_id)?.name}</h2></div><Status value={o.fulfillment_status}/></header><div className="order-flow">{['Requirements','Purchasing','Receiving','Staging','Delivery','Accounting'].map((x,i)=><span className={i<=1?'done':''} key={x}>{x}</span>)}</div><div className="order-stats"><div><small>Order total</small><strong>{fmtMoney(o.total)}</strong></div><div><small>Open POs</small><strong>{data.purchase_orders.filter(p=>p.order_id===o.id).length}</strong></div><div><small>Delivery</small><strong>{o.delivery_required===false?'Not required':'Required'}</strong></div><div><small>Accounting</small><strong>{o.accounting_ready?'Ready':'Waiting'}</strong></div></div></article>)}</section></>}
function Receiving({data}){return <><PageIntro eyebrow="RECEIVING" title="Verify what arrived before custody changes." copy="PO context, discrepancies, photos, packing slips and warehouse destinations are completed as one controlled action."/><section className="receiving-sheet"><header><div><small>RECEIVING AGAINST</small><h2>{data.purchase_orders[0]?.po_number||'No open PO'}</h2></div><Status value="in_progress"/></header><div className="receiving-head"><span>Item</span><span>Ordered</span><span>Received</span><span>Condition</span><span>Destination</span></div>{[['Prime mat roll · Charcoal','1','1','Good','STG-A'],['Black edging','120 LF','120 LF','Good','STG-A'],['Logo insert','1','0','Short','Exception Hold']].map(x=><div className="receiving-row" key={x[0]}>{x.map(v=><span key={v}>{v}</span>)}</div>)}<footer><button className="secondary">Add discrepancy photos</button><button className="primary">Complete receipt</button></footer></section></>}
function WarehouseWorkspace({data}){return <><PageIntro eyebrow="WAREHOUSE" title="Custody, location and readiness by destination." copy="Inventory and staging are organized around orders—not disconnected stock cards."/><div className="warehouse-board">{['Receiving Dock','Staging A','Staging B','Ready to Load'].map((lane,i)=><section key={lane}><header><strong>{lane}</strong><span>{[3,4,2,2][i]}</span></header>{[['ORD-26101','Morrice Area Schools','Custodial supplies'],['ORD-26114','Saranac Community Schools','Main gym materials']].slice(0,i===0?1:2).map(x=><article key={x[0]+lane}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p><footer><span>{lane}</span><ChevronRight/></footer></article>)}</section>)}</div></>}
function DeliveryWorkspace({data,advanceRecord}){return <><PageIntro eyebrow="FINISHLINE DELIVERY" title="Schedule, load and prove completion." copy="Ticket detail, mobile proof and accounting readiness remain connected to OrderDNA."/><div className="delivery-layout"><section className="delivery-queue panel">{data.delivery_tickets.map(d=><article key={d.id}><div><small>{d.ticket_number}</small><strong>{data.customers.find(c=>c.id===d.customer_id)?.name}</strong><span>{data.facilities.find(f=>f.id===d.facility_id)?.name}</span></div><Status value={d.status}/></article>)}</section><section className="delivery-ticket"><header><div><span>DELIVERY TICKET</span><h2>{data.delivery_tickets[0]?.ticket_number||'No ticket'}</h2></div><div className="qr-placeholder">QR</div></header><div className="ticket-destination"><Truck/><div><strong>{data.customers.find(c=>c.id===data.delivery_tickets[0]?.customer_id)?.name}</strong><span>{data.facilities.find(f=>f.id===data.delivery_tickets[0]?.facility_id)?.name}</span></div></div><div className="ticket-items"><div><Check/>Cleaning chemicals · 12 cases</div><div><Check/>Mop frames and handles · 8</div><div><Check/>Replacement mop heads · 24</div></div><footer><button className="secondary">Print ticket</button><button className="primary" onClick={()=>data.delivery_tickets[0]&&advanceRecord('delivery_tickets',data.delivery_tickets[0].id,'completed')}>Capture proof & complete</button></footer></section></div></>}

function FieldWorkspace(){return <><PageIntro eyebrow="FIELD OPERATIONS" title="Today’s assignment is the workspace." copy="Crew, vehicle, site instructions, required forms, proof and safety actions optimized for mobile use."/><div className="field-day"><header><div><small>TUESDAY · AUGUST 4</small><h2>Saranac Main Gym</h2><p>Sand & refinish · Surface preparation phase</p></div><Status value="on_track"/></header><div className="field-grid"><section><span>CREW & VEHICLE</span><div className="crew-person"><Users/><div><strong>Justin Warner · Lead</strong><small>Gerry · Brandon M · Andrew V</small></div></div><div className="crew-person"><Truck/><div><strong>Truck 12 · Trailer 4</strong><small>Pre-trip inspection complete</small></div></div></section><section><span>SITE INTELLIGENCE</span><p>Main receiving entrance opens at 6:30 AM. Protect south hallway and use auxiliary power panel near stage.</p><button className="secondary">Open FacilityDNA instructions</button></section><section><span>REQUIRED COMPLETION</span>{['Daily safety form','Before photos','Moisture readings','End-of-day proof'].map(x=><label key={x}><input type="checkbox"/>{x}</label>)}</section></div><footer><button className="secondary">Report issue</button><button className="primary">Start field workflow</button></footer></div></>}
function ContractsWorkspace({data}){return <><PageIntro eyebrow="CONTRACTOPS" title="Billing and compliance on the same project record." copy="SOV, pay applications, bonds, waivers, signatures, notary routing and payment history stay connected."/><div className="contract-layout"><section className="contract-list panel">{data.contracts.map(c=><button key={c.id}><div><small>{c.contract_number}</small><strong>{c.general_contractor}</strong><span>{fmtMoney(c.contract_value)}</span></div><Status value={c.status}/></button>)}</section><section className="contract-workspace"><header className="record-header"><div className="identity-icon"><FileCheck2/></div><div><small>{data.contracts[0]?.contract_number}</small><h2>{data.projects.find(p=>p.id===data.contracts[0]?.project_id)?.name}</h2><p>{data.contracts[0]?.general_contractor}</p></div><Status value="controller_review"/></header><div className="contract-metrics"><div><small>Contract value</small><strong>{fmtMoney(data.contracts[0]?.contract_value)}</strong></div><div><small>Billed to date</small><strong>{fmtMoney(data.contracts[0]?.billed_to_date)}</strong></div><div><small>Paid to date</small><strong>{fmtMoney(data.contracts[0]?.paid_to_date)}</strong></div><div><small>Remaining</small><strong>{fmtMoney((data.contracts[0]?.contract_value||0)-(data.contracts[0]?.billed_to_date||0))}</strong></div></div><div className="payapp-flow">{['PM Update','Controller Review','Authorized Signer','Notary','Ready to Submit','Submitted','Approved','Paid'].map((x,i)=><span className={i<2?'done':i===2?'active':''} key={x}>{x}</span>)}</div><div className="contract-actions"><section><span>COMPLIANCE READINESS</span>{['Current W-9','Certificate of insurance','Signed subcontract','Conditional waiver'].map((x,i)=><div key={x}><Check/>{x}<Status value={i===3?'waiting':'complete'}/></div>)}</section><aside><AlertTriangle/><h3>One blocker remains</h3><p>Conditional waiver is required before this pay application can be submitted.</p><button className="primary">Request missing waiver</button></aside></div></section></div></>}
function ReportsWorkspace({data}){return <><PageIntro eyebrow="SCORECENTER" title="Operational intelligence from authoritative records." copy="Performance drill-down without a chart-first homepage or copied reporting database."/><div className="score-metrics">{[['Pipeline value','$2.84M','+11%'],['Active projects',String(data.projects.length||27),'6 moving today'],['Orders at risk','2','Vendor dates'],['Contract health','94%','Strong']].map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div><div className="report-grid"><section className="panel"><header><span>LIFECYCLE THROUGHPUT</span><h3>Records by stage</h3></header>{FLOW.map((x,i)=><div className="report-bar" key={x}><span>{x}</span><div><i style={{width:`${[38,55,68,33,24,72,21,47,60,43,29,36,18][i]}%`}}/></div><strong>{[8,12,15,7,5,16,4,10,13,9,6,8,4][i]}</strong></div>)}</section><section className="panel"><header><span>EXCEPTION ANALYSIS</span><h3>What is holding work</h3></header>{[['Vendor date changed','2 records','Purchasing'],['Missing customer approval','5 records','Sales'],['Crew conflict','1 project','Field'],['Compliance document missing','3 contracts','Contracts']].map(x=><div className="exception-row" key={x[0]}><AlertTriangle/><div><strong>{x[0]}</strong><small>{x[2]}</small></div><span>{x[1]}</span></div>)}</section></div></>}
function AdministrationWorkspace({context}){if(context==='Price Book')return <PriceBook/>;return <><PageIntro eyebrow="PLATFORM ADMINISTRATION" title="Control the shared operating system." copy="Users, permissions, workflow rules, templates, documents, integrations and audit—not a collection of app settings."/><div className="admin-grid">{[['Users & roles','One identity, role sets, teams and manager scope',Users],['Workflow builder','Stages, ownership, approvals and handoffs',Workflow],['Templates','Quote, proposal, task and document standards',FileText],['Document controls','Types, versions, visibility and retention',Archive],['Integrations','QuickBooks, email, calendar, storage and carriers',Grid2X2],['Audit','Immutable changes, approvals and system actions',Activity]].map(([a,b,I])=><button key={a}><I/><div><strong>{a}</strong><span>{b}</span></div><ChevronRight/></button>)}</div></>}
function PriceBook(){return <><PageIntro eyebrow="PRICE BOOK" title="Master cost and pricing infrastructure." copy="Compact item management only. Quote Playbook consumes controlled pricing snapshots."/><div className="pricebook-layout"><section className="pricebook-table"><header><div className="list-filter"><Search/><input placeholder="Search products, services or SKUs"/></div></header><div className="pricebook-head"><span>Item</span><span>Category</span><span>Vendor</span><span>Cost</span><span>Published price</span></div>{[['MAT-PRIME-67','Prime Entrance Mat','Matting','Matter Surfaces','$12.40/SF','$21.50/SF'],['FIN-BONA-TF','Bona Traffic HD','Finish','Bona US','$116.00','$169.00'],['LAB-SAND','Sports floor sanding labor','Labor','Internal','$2.85/SF','$5.95/SF']].map(x=><button key={x[0]}>{x.map(v=><span key={v}>{v}</span>)}</button>)}</section><aside className="pricebook-detail"><span>SELECTED ITEM</span><h2>Prime Entrance Mat</h2><small>MAT-PRIME-67 · Published</small><dl><div><dt>Current cost</dt><dd>$12.40/SF</dd></div><div><dt>Published price</dt><dd>$21.50/SF</dd></div><div><dt>Gross margin</dt><dd>42.3%</dd></div><div><dt>Vendor</dt><dd>Matter Surfaces</dd></div></dl><button className="primary">Edit controlled pricing</button></aside></div></>}

function NotificationCenter({tasks,close,goTask}){return <div className="notification-panel"><header><div><small>NOTIFICATIONS</small><h3>Exact actions requiring attention</h3></div><button className="icon-button" onClick={close}><X/></button></header>{tasks.filter(t=>t.status!=='complete').slice(0,6).map(t=><button key={t.id} onClick={goTask}><span className="notice-dot"/><div><strong>{t.title}</strong><small>{pretty(t.status)} · {pretty(t.priority)}</small></div><ChevronRight/></button>)}</div>}
function GlobalSearch({data,close,navigate}){const [q,setQ]=useState('');const results=useMemo(()=>{if(!q)return[];const s=q.toLowerCase();return [...data.customers.filter(x=>x.name.toLowerCase().includes(s)).map(x=>({type:'customer',id:x.id,title:x.name,meta:x.customer_number})),...data.sales_requests.filter(x=>(x.title+' '+x.need_summary).toLowerCase().includes(s)).map(x=>({type:'request',id:x.id,title:x.title,meta:x.request_number}))].slice(0,12)},[q,data]);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="search-modal"><header><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers, facilities, spaces, requests, quotes, projects, orders, deliveries and contracts"/><kbd>ESC</kbd></header>{q?<div className="search-results">{results.length?results.map(r=><button key={r.type+r.id} onClick={()=>navigate(r.type,r.id)}><span>{pretty(r.type)}</span><div><strong>{r.title}</strong><small>{r.meta}</small></div><ChevronRight/></button>):<Empty title="No matching records" copy="Try a customer, facility, request number or project name."/>}</div>:<div className="search-guidance"><Command/><h2>Search the entire company.</h2><p>One index over the same authoritative FCC Ops records.</p></div>}</div></div>}
function CreateCenter({data,close,createTask,createRequest}){const [type,setType]=useState('request');const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{if(type==='task')await createTask({title:f.get('title'),description:f.get('description'),priority:f.get('priority'),due_at:f.get('due_at')||null});else await createRequest({title:f.get('title'),need_summary:f.get('description'),request_type:f.get('request_type'),customer_id:f.get('customer_id'),facility_id:f.get('facility_id'),space_id:f.get('space_id')||null,priority:f.get('priority')});close()}catch(err){alert(err.message)}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="create-modal"><header><div><small>UNIVERSAL CREATE</small><h2>Start work with the right record context.</h2></div><button className="icon-button" onClick={close}><X/></button></header><nav><button className={type==='request'?'active':''} onClick={()=>setType('request')}>Sales request</button><button className={type==='task'?'active':''} onClick={()=>setType('task')}>Task</button></nav><form onSubmit={submit}><label>Title<input required name="title" placeholder={type==='task'?'What needs to happen?':'Describe the customer need'}/></label><label>Details<textarea required name="description" rows="4" placeholder="Capture enough context for the next person to act without chasing information."/></label>{type==='request'&&<><div className="form-grid"><label>Customer<select name="customer_id" required>{data.customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Facility<select name="facility_id" required>{data.facilities.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label></div><div className="form-grid"><label>Space<select name="space_id"><option value="">Multiple / not selected</option>{data.spaces.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Request type<select name="request_type"><option value="service">Service project</option><option value="resale">Resale products</option><option value="matting">Custom matting</option><option value="design">Court design</option></select></label></div></>}{type==='task'&&<label>Due date<input type="datetime-local" name="due_at"/></label>}<label>Priority<select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?<Loader2 className="spin"/>:<Plus/>} Create {type}</button></footer></form></div></div>}
